os: linux
dist: bionic
sudo: True
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"

addons:
  apt:
    update: True

before_script:
  - sudo apt install python3 python3-venv sqlite3 libsqlite3-dev

install:
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  - pip install codecov nose
  - source make_env

script:
  - nosetests --with-coverage --cover-erase --cover-package=app
  - codecov

